name: Render Jupyter Notebook

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install nbconvert
      - name: Convert to HTML
        run: |
          pwd # Print the current working directory
          ls -l # List files in the current directory
          jupyter nbconvert --to html Assignment_Submission_Prabhath_Data_Science.ipynb --output output.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
